name: QRtendance
description: QRtendance.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  firebase_auth: 0.6.6
  google_sign_in: ^3.2.4
  flutter_facebook_login: 1.1.1
  cloud_firestore: 0.7.4 #0.8.2+3 error with barcode
  rxdart: 0.20.0
  after_layout: ^1.0.7
  flutter_masked_text: ^0.7.0
  date_format: ^1.0.6
  flutter_swiper : ^1.1.4
  numberpicker: ^1.0.0
  random_color: ^1.0.3
  barcode_scan: 0.0.8
  mlkit: 0.8.3
  image_picker: 0.4.10
  flutter_slidable: ^0.4.9
  charts_flutter: ^0.6.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: 'assets/logo/icon.png'
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo/facebook.png
   - assets/logo/google.png
   - assets/logo/logo.png
   - assets/images/background.png
   - assets/images/scan_card.png
   - assets/images/student_card_sample.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand_Dash.otf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.otf
          weight: 700
        - asset: assets/fonts/Quicksand/Quicksand-BoldItalic.otf
          weight: 700
        - asset: assets/fonts/Quicksand/Quicksand-Italic.otf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Light.otf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-LightItalic.otf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Regular.otf
          weight: 400
    - family: Exo_2
      fonts:
        - asset: assets/fonts/Exo_2/Exo2-Black.ttf
          weight: 900
        - asset: assets/fonts/Exo_2/Exo2-BlackItalic.ttf
          weight: 900
        - asset: assets/fonts/Exo_2/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo_2/Exo2-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Exo_2/Exo2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Exo_2/Exo2-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Exo_2/Exo2-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Exo_2/Exo2-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Exo_2/Exo2-Italic.ttf
          weight: 400
        - asset: assets/fonts/Exo_2/Exo2-Light.ttf
          weight: 200
        - asset: assets/fonts/Exo_2/Exo2-LightItalic.ttf
          weight: 200
        - asset: assets/fonts/Exo_2/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo_2/Exo2-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Exo_2/Exo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Exo_2/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo_2/Exo2-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Exo_2/Exo2-Thin.ttf
          weight: 100
        - asset: assets/fonts/Exo_2/Exo2-ThinItalic.ttf
          weight: 100

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Black.ttf
          weight: 900
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Italic.ttf
          weight: 400
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Light.ttf
          weight: 300
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-Regular.ttf
          weight: 400
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/TitilliumWeb/TitilliumWeb-SemiBoldItalic.ttf
          weight: 600
        
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound/VarelaRound-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
